### ISSUE TITLE
Question about formatting fat32

### ISSUE THREAD

**Issue by linuxplayground** [gfoot/sdcard6502#3]
Hi

How specifically are you formatting these SD cards so that they meet the requirements of the fat32 library?

I can read the mbr (first sector and verify 55 AA ) but then I always fail after that. Doing a hexdump of the card shows the partition type as 0b (11).  Not 12.

If I go ahead and set the partition type to 11 and run again it fails on stage 2.  Last two bytes in the block are 55 and ff. I believe this to be the sector containing the BPB.

**Comment by gfoot** [comment]
Hi David

Type 11 seems to be using CHS (cylinder/head/sector) addressing rather than
LBA. It seems very odd for an SD card. I'm surprised if any system actually
formats SD cards that way as it's quite an obsolete way of doing things, it
only really made sense on early physical hard disks.

I'm not sure what changes between the two types in practice, but I would
guess possibly the way the partition start is specified in the partition
table, and possibly some fields within the FAT32 filesystem itself.
Hopefully not too much though!

**Comment by linuxplayground** [comment]
Thanks for the reply. 

I'm in the process now of zeroing the whole card to get rid of noise.  So I can actually match the bytes on the card with the spec.

 I think fdisk allows for setting the partition table to lba format.  I'll try that.

**Comment by gfoot** [comment]
Yes you can just use fdisk or gparted to change the partition type, and
then run mkfs.vfat or whatever it's called to format it. I don't remember
whether I formatted mine under Linux or Windows. The built in format tool
in Windows actual can't format large SD cards as FAT32 anyway, you need
third party tools for that.

**Comment by linuxplayground** [comment]
Okay. I got it working. I used my little netbook running debian to format the card with fat32 lba mbr and one partition. It's an 8gb sdhc. 

I had to port your code to ca65 to get it to work on my setup. (I'm running OS/1 from dbuchwald). 

I think some of the issues I was having were to do with trying to port the code. After a break and a redo, it's all working. I've learned loads from this project. Thanks very much.
